const { MongoClient } = require('mongodb');

const courses = [
  // 5-7-ci siniflər üçün kurslar
  {
    title: '5-7-ci siniflər: Azərbaycan dili',
    description: 'Fonetika, leksika, morfoloji təhlil. Oxu və yazı bacarıqlarının inkişafı. 48 saatlıq kurs.',
    slug: '5-7-ci-sinifler-azerbaycan-dili',
    icon: 'Book',
    color: 'blue',
    href: '/kurslar/5-7-ci-sinifler',
    features: ['24 dərs', '48 saat', 'Müəllim: Leyla Əhmədova', 'Yaşa uyğun proqram'],
    duration: '9 ay',
    students: '50+',
    displayOrder: 0,
    isActive: true,
    fullDescription: 'Bu kurs 5-7-ci sinif şagirdləri üçün Azərbaycan dili fənninin tam mənimsənilməsinə yönəlib. Fonetika, leksika, morfoloji təhlil mövzuları əhatə olunur.',
    lessons: 24,
    hours: 48,
    teacher: 'Leyla Əhmədova',
    price: '150 AZN',
    program: ['Fonetika', 'Leksika', 'Morfoloji təhlil', 'Oxu bacarıqları', 'Yazı bacarıqları'],
    requirements: ['5-7-ci sinif şagirdləri üçün'],
    outcomes: ['Oxu və yazı bacarıqlarının inkişafı', 'Qrammatika biliklərinin artırılması'],
    targetAudience: '5-7-ci sinif şagirdləri',
    level: 'Başlanğıc',
    certificate: false,
  },
  {
    title: '5-7-ci siniflər: Riyaziyyat',
    description: 'Ədədlər, həndəsi fiqurlar, kəsrlər, faizlər. Məntiqi təfəkkürün inkişafı. 64 saatlıq kurs.',
    slug: '5-7-ci-sinifler-riyaziyyat',
    icon: 'Book',
    color: 'blue',
    href: '/kurslar/5-7-ci-sinifler',
    features: ['32 dərs', '64 saat', 'Müəllim: Rəşad Məmmədov', 'Praktik məsələlər'],
    duration: '9 ay',
    students: '45+',
    displayOrder: 1,
    isActive: true,
    fullDescription: '5-7-ci siniflər üçün riyaziyyat kursu. Ədədlər, həndəsi fiqurlar, kəsrlər, faizlər kimi mövzular əhatə olunur.',
    lessons: 32,
    hours: 64,
    teacher: 'Rəşad Məmmədov',
    price: '150 AZN',
    program: ['Ədədlər', 'Həndəsi fiqurlar', 'Kəsrlər', 'Faizlər', 'Məntiqi məsələlər'],
    requirements: ['5-7-ci sinif şagirdləri üçün'],
    outcomes: ['Məntiqi təfəkkürün inkişafı', 'Riyazi bacarıqların artırılması'],
    targetAudience: '5-7-ci sinif şagirdləri',
    level: 'Başlanğıc',
    certificate: false,
  },
  {
    title: '5-7-ci siniflər: İngilis dili',
    description: 'Əlifba, əsas sözlər, sadə cümlələr. Danışıq və yazı bacarıqları. 48 saatlıq kurs.',
    slug: '5-7-ci-sinifler-ingilis-dili',
    icon: 'Globe',
    color: 'blue',
    href: '/kurslar/5-7-ci-sinifler',
    features: ['24 dərs', '48 saat', 'Müəllim: Aysel Kərimova', 'Danışıq praktikası'],
    duration: '9 ay',
    students: '40+',
    displayOrder: 2,
    isActive: true,
    fullDescription: '5-7-ci siniflər üçün ingilis dili kursu. Əlifba, əsas sözlər, sadə cümlələr öyrədilir.',
    lessons: 24,
    hours: 48,
    teacher: 'Aysel Kərimova',
    price: '150 AZN',
    program: ['Əlifba', 'Əsas sözlər', 'Sadə cümlələr', 'Danışıq praktikası', 'Yazı praktikası'],
    requirements: ['5-7-ci sinif şagirdləri üçün'],
    outcomes: ['Danışıq və yazı bacarıqlarının inkişafı'],
    targetAudience: '5-7-ci sinif şagirdləri',
    level: 'Başlanğıc',
    certificate: false,
  },
  {
    title: '5-7-ci siniflər: Tarix',
    description: 'Azərbaycan tarixi, qədim dövlətlər, mədəniyyət abidələri. 32 saatlıq kurs.',
    slug: '5-7-ci-sinifler-tarix',
    icon: 'Book',
    color: 'blue',
    href: '/kurslar/5-7-ci-sinifler',
    features: ['16 dərs', '32 saat', 'Müəllim: Elşən Hüseynov', 'İnteraktiv dərslər'],
    duration: '9 ay',
    students: '35+',
    displayOrder: 3,
    isActive: true,
    fullDescription: '5-7-ci siniflər üçün Azərbaycan tarixi kursu. Qədim dövlətlər, mədəniyyət abidələri öyrədilir.',
    lessons: 16,
    hours: 32,
    teacher: 'Elşən Hüseynov',
    price: '120 AZN',
    program: ['Azərbaycan tarixi', 'Qədim dövlətlər', 'Mədəniyyət abidələri'],
    requirements: ['5-7-ci sinif şagirdləri üçün'],
    outcomes: ['Tarixi biliklərin artırılması'],
    targetAudience: '5-7-ci sinif şagirdləri',
    level: 'Başlanğıc',
    certificate: false,
  },
  
  // 8-9-cu siniflər üçün kurslar
  {
    title: '8-9-cu siniflər: Azərbaycan dili (Attestat)',
    description: '9-cu sinif attestat imtahanına tam hazırlıq. Bütün mövzular əhatə olunur.',
    slug: '8-9-cu-sinifler-azerbaycan-dili-attestat',
    icon: 'Target',
    color: 'green',
    href: '/kurslar/8-9-cu-sinifler',
    features: ['Attestat hazırlığı', '36 dərs', 'Sınaq imtahanları', 'Fərdi yanaşma'],
    duration: '9 ay',
    students: '60+',
    displayOrder: 4,
    isActive: true,
    fullDescription: '9-cu sinif attestat imtahanına tam hazırlıq kursu. Bütün qrammatika mövzuları əhatə olunur.',
    lessons: 36,
    hours: 72,
    teacher: 'Gülnarə Əliyeva',
    price: '180 AZN',
    program: ['Qrammatika', 'İnşa', 'Test mərkəzi', 'Sınaq imtahanları'],
    requirements: ['8-9-cu sinif şagirdləri üçün'],
    outcomes: ['Attestat imtahanına hazır olmaq'],
    targetAudience: '8-9-cu sinif şagirdləri',
    level: 'Orta',
    certificate: true,
  },
  {
    title: '8-9-cu siniflər: Riyaziyyat (Attestat)',
    description: 'Əsas fənnlər üzrə dərinləşdirilmiş tədris və attestat hazırlığı.',
    slug: '8-9-cu-sinifler-riyaziyyat-attestat',
    icon: 'Target',
    color: 'green',
    href: '/kurslar/8-9-cu-sinifler',
    features: ['40 dərs', 'Cəbr və həndəsə', 'Test mərkəzi', 'Ev tapşırıqları'],
    duration: '9 ay',
    students: '55+',
    displayOrder: 5,
    isActive: true,
    fullDescription: '8-9-cu siniflər üçün riyaziyyat attestat hazırlığı. Cəbr və həndəsə mövzuları əhatə olunur.',
    lessons: 40,
    hours: 80,
    teacher: 'Rəşad Məmmədov',
    price: '180 AZN',
    program: ['Cəbr', 'Həndəsə', 'Test mərkəzi', 'Sınaq imtahanları'],
    requirements: ['8-9-cu sinif şagirdləri üçün'],
    outcomes: ['Attestat imtahanına hazır olmaq'],
    targetAudience: '8-9-cu sinif şagirdləri',
    level: 'Orta',
    certificate: true,
  },
  {
    title: '8-9-cu siniflər: Fizika',
    description: 'Fizika fənninin əsasları və attestat imtahanına hazırlıq.',
    slug: '8-9-cu-sinifler-fizika',
    icon: 'Target',
    color: 'green',
    href: '/kurslar/8-9-cu-sinifler',
    features: ['30 dərs', 'Laboratoriya işləri', 'Praktik məsələlər', 'Sınaqlar'],
    duration: '9 ay',
    students: '40+',
    displayOrder: 6,
    isActive: true,
    fullDescription: '8-9-cu siniflər üçün fizika kursu. Mexanika, elektrik, maqnetizm mövzuları əhatə olunur.',
    lessons: 30,
    hours: 60,
    teacher: 'Elşən Hüseynov',
    price: '160 AZN',
    program: ['Mexanika', 'Elektrik', 'Maqnetizm', 'Laboratoriya işləri'],
    requirements: ['8-9-cu sinif şagirdləri üçün'],
    outcomes: ['Fizika biliklərinin artırılması'],
    targetAudience: '8-9-cu sinif şagirdləri',
    level: 'Orta',
    certificate: true,
  },
  {
    title: '8-9-cu siniflər: Kimya',
    description: 'Kimya fənninin əsasları və attestat imtahanına hazırlıq.',
    slug: '8-9-cu-sinifler-kimya',
    icon: 'Target',
    color: 'green',
    href: '/kurslar/8-9-cu-sinifler',
    features: ['28 dərs', 'Laboratoriya', 'Reaksiyalar', 'Praktik məşğələlər'],
    duration: '9 ay',
    students: '35+',
    displayOrder: 7,
    isActive: true,
    fullDescription: '8-9-cu siniflər üçün kimya kursu. Üzvi və qeyri-üzvi kimya əsasları öyrədilir.',
    lessons: 28,
    hours: 56,
    teacher: 'Nigar Məmmədova',
    price: '160 AZN',
    program: ['Üzvi kimya', 'Qeyri-üzvi kimya', 'Reaksiyalar', 'Laboratoriya işləri'],
    requirements: ['8-9-cu sinif şagirdləri üçün'],
    outcomes: ['Kimya biliklərinin artırılması'],
    targetAudience: '8-9-cu sinif şagirdləri',
    level: 'Orta',
    certificate: true,
  },
  
  // 10-11-ci siniflər üçün kurslar
  {
    title: '10-11-ci siniflər: Riyaziyyat (Qəbul)',
    description: 'Universitet qəbul imtahanlarına tam hazırlıq. Cəbr, həndəsə, funksiyalar.',
    slug: '10-11-ci-sinifler-riyaziyyat-qebul',
    icon: 'GraduationCap',
    color: 'red',
    href: '/kurslar/10-11-ci-sinifler',
    features: ['50 dərs', 'Hər ay sınaq', 'Test texnikaları', 'Fərdi plan'],
    duration: '2 il',
    students: '80+',
    displayOrder: 8,
    isActive: true,
    fullDescription: '10-11-ci siniflər üçün riyaziyyat qəbul hazırlığı. Cəbr, həndəsə, funksiyalar mövzuları əhatə olunur.',
    lessons: 50,
    hours: 100,
    teacher: 'Rəşad Məmmədov',
    price: '300 AZN',
    program: ['Cəbr', 'Həndəsə', 'Funksiyalar', 'Test texnikaları'],
    requirements: ['10-11-ci sinif şagirdləri üçün'],
    outcomes: ['Qəbul imtahanına hazır olmaq'],
    targetAudience: '10-11-ci sinif şagirdləri',
    level: 'İrəli',
    certificate: true,
  },
  {
    title: '10-11-ci siniflər: Azərbaycan dili (Qəbul)',
    description: 'Qəbul imtahanlarına tam hazırlıq. Bütün qrammatika mövzuları.',
    slug: '10-11-ci-sinifler-azerbaycan-dili-qebul',
    icon: 'GraduationCap',
    color: 'red',
    href: '/kurslar/10-11-ci-sinifler',
    features: ['45 dərs', 'İnşa praktikası', 'Test mərkəzi', 'Sınaqlar'],
    duration: '2 il',
    students: '75+',
    displayOrder: 9,
    isActive: true,
    fullDescription: '10-11-ci siniflər üçün Azərbaycan dili qəbul hazırlığı. Bütün qrammatika mövzuları və inşa praktikası.',
    lessons: 45,
    hours: 90,
    teacher: 'Gülnarə Əliyeva',
    price: '300 AZN',
    program: ['Qrammatika', 'İnşa', 'Test mərkəzi', 'Sınaq imtahanları'],
    requirements: ['10-11-ci sinif şagirdləri üçün'],
    outcomes: ['Qəbul imtahanına hazır olmaq'],
    targetAudience: '10-11-ci sinif şagirdləri',
    level: 'İrəli',
    certificate: true,
  },
  {
    title: '10-11-ci siniflər: Fizika (Qəbul)',
    description: 'Qəbul imtahanlarına tam hazırlıq. Mexanika, elektrik, maqnetizm.',
    slug: '10-11-ci-sinifler-fizika-qebul',
    icon: 'GraduationCap',
    color: 'red',
    href: '/kurslar/10-11-ci-sinifler',
    features: ['48 dərs', 'Laboratoriya', 'Mürəkkəb məsələlər', 'Sınaqlar'],
    duration: '2 il',
    students: '60+',
    displayOrder: 10,
    isActive: true,
    fullDescription: '10-11-ci siniflər üçün fizika qəbul hazırlığı. Mexanika, elektrik, maqnetizm mövzuları əhatə olunur.',
    lessons: 48,
    hours: 96,
    teacher: 'Elşən Hüseynov',
    price: '300 AZN',
    program: ['Mexanika', 'Elektrik', 'Maqnetizm', 'Optika'],
    requirements: ['10-11-ci sinif şagirdləri üçün'],
    outcomes: ['Qəbul imtahanına hazır olmaq'],
    targetAudience: '10-11-ci sinif şagirdləri',
    level: 'İrəli',
    certificate: true,
  },
  {
    title: '10-11-ci siniflər: Kimya (Qəbul)',
    description: 'Qəbul imtahanlarına tam hazırlıq. Üzvi və qeyri-üzvi kimya.',
    slug: '10-11-ci-sinifler-kimya-qebul',
    icon: 'GraduationCap',
    color: 'red',
    href: '/kurslar/10-11-ci-sinifler',
    features: ['45 dərs', 'Reaksiyalar', 'Praktik məşğələlər', 'Testlər'],
    duration: '2 il',
    students: '50+',
    displayOrder: 11,
    isActive: true,
    fullDescription: '10-11-ci siniflər üçün kimya qəbul hazırlığı. Üzvi və qeyri-üzvi kimya mövzuları əhatə olunur.',
    lessons: 45,
    hours: 90,
    teacher: 'Nigar Məmmədova',
    price: '300 AZN',
    program: ['Üzvi kimya', 'Qeyri-üzvi kimya', 'Reaksiyalar', 'Hesablama məsələləri'],
    requirements: ['10-11-ci sinif şagirdləri üçün'],
    outcomes: ['Qəbul imtahanına hazır olmaq'],
    targetAudience: '10-11-ci sinif şagirdləri',
    level: 'İrəli',
    certificate: true,
  },
  {
    title: '10-11-ci siniflər: Biologiya (Qəbul)',
    description: 'Qəbul imtahanlarına tam hazırlıq. Botanika, zoologiya, anatomiya.',
    slug: '10-11-ci-sinifler-biologiya-qebul',
    icon: 'GraduationCap',
    color: 'red',
    href: '/kurslar/10-11-ci-sinifler',
    features: ['42 dərs', 'Laboratoriya', 'Mikroskop', 'Sınaqlar'],
    duration: '2 il',
    students: '45+',
    displayOrder: 12,
    isActive: true,
    fullDescription: '10-11-ci siniflər üçün biologiya qəbul hazırlığı. Botanika, zoologiya, anatomiya mövzuları əhatə olunur.',
    lessons: 42,
    hours: 84,
    teacher: 'Aysel Kərimova',
    price: '300 AZN',
    program: ['Botanika', 'Zoologiya', 'Anatomiya', 'Ümumi biologiya'],
    requirements: ['10-11-ci sinif şagirdləri üçün'],
    outcomes: ['Qəbul imtahanına hazır olmaq'],
    targetAudience: '10-11-ci sinif şagirdləri',
    level: 'İrəli',
    certificate: true,
  },
  
  // Ekspress-kurs
  {
    title: 'Ekspress: Riyaziyyat',
    description: '3 ayda riyaziyyat üzrə intensiv hazırlıq. Qəbul imtahanına qısa yol.',
    slug: 'ekspress-riyaziyyat',
    icon: 'Zap',
    color: 'yellow',
    href: '/kurslar/ekspress-kurs',
    features: ['3 ay', 'Gündə 4 saat', 'Test texnikaları', 'Bal artımı 200-300'],
    duration: '3 ay',
    students: '30+',
    displayOrder: 13,
    isActive: true,
    fullDescription: '3 ayda riyaziyyat üzrə intensiv hazırlıq. Qəbul imtahanına qısa yol.',
    lessons: 60,
    hours: 120,
    teacher: 'Rəşad Məmmədov',
    price: '250 AZN',
    program: ['Cəbr', 'Həndəsə', 'Test texnikaları', 'Sınaq imtahanları'],
    requirements: ['10-11-ci sinif şagirdləri üçün'],
    outcomes: ['Qəbul imtahanına hazır olmaq'],
    targetAudience: '10-11-ci sinif şagirdləri',
    level: 'Hər səviyyə',
    certificate: true,
  },
  {
    title: 'Ekspress: Azərbaycan dili',
    description: '3 ayda Azərbaycan dili üzrə intensiv hazırlıq.',
    slug: 'ekspress-azerbaycan-dili',
    icon: 'Zap',
    color: 'yellow',
    href: '/kurslar/ekspress-kurs',
    features: ['3 ay', 'Qrammatika', 'İnşa', 'Sınaqlar'],
    duration: '3 ay',
    students: '35+',
    displayOrder: 14,
    isActive: true,
    fullDescription: '3 ayda Azərbaycan dili üzrə intensiv hazırlıq. Bütün qrammatika mövzuları və inşa praktikası.',
    lessons: 45,
    hours: 90,
    teacher: 'Gülnarə Əliyeva',
    price: '250 AZN',
    program: ['Qrammatika', 'İnşa', 'Test mərkəzi', 'Sınaq imtahanları'],
    requirements: ['10-11-ci sinif şagirdləri üçün'],
    outcomes: ['Qəbul imtahanına hazır olmaq'],
    targetAudience: '10-11-ci sinif şagirdləri',
    level: 'Hər səviyyə',
    certificate: true,
  },
  
  // Rus bölməsi üçün Azərbaycan dili
  {
    title: 'Rus bölməsi: Azərbaycan dili (Başlanğıc)',
    description: 'Rusdilli şagirdlər üçün Azərbaycan dili öyrənmə kursu. Başlanğıc səviyyə.',
    slug: 'rus-bolmesi-azerbaycan-dili-baslangic',
    icon: 'Globe',
    color: 'pink',
    href: '/kurslar/rus-bolmesi-ucun-azerbaycan-dili',
    features: ['40 dərs', 'Əlifba', 'Danışıq', 'Müqayisəli metodika'],
    duration: '10 ay',
    students: '40+',
    displayOrder: 15,
    isActive: true,
    fullDescription: 'Rusdilli şagirdlər üçün Azərbaycan dili öyrənmə kursu. Başlanğıc səviyyədən başlayaraq.',
    lessons: 40,
    hours: 80,
    teacher: 'Aysel Kərimova',
    price: '200 AZN',
    program: ['Əlifba', 'Əsas sözlər', 'Sadə cümlələr', 'Danışıq praktikası'],
    requirements: ['Rus dili bilən şagirdlər üçün'],
    outcomes: ['Azərbaycan dilində danışa bilmək'],
    targetAudience: 'Rus bölməsi şagirdləri',
    level: 'Başlanğıc',
    certificate: true,
  },
  {
    title: 'Rus bölməsi: Azərbaycan dili (Orta)',
    description: 'Rusdilli şagirdlər üçün Azərbaycan dili. Orta səviyyə.',
    slug: 'rus-bolmesi-azerbaycan-dili-orta',
    icon: 'Globe',
    color: 'pink',
    href: '/kurslar/rus-bolmesi-ucun-azerbaycan-dili',
    features: ['35 dərs', 'Qrammatika', 'Danışıq klubları', 'Sertifikat'],
    duration: '10 ay',
    students: '35+',
    displayOrder: 16,
    isActive: true,
    fullDescription: 'Rusdilli şagirdlər üçün Azərbaycan dili orta səviyyə kursu.',
    lessons: 35,
    hours: 70,
    teacher: 'Aysel Kərimova',
    price: '200 AZN',
    program: ['Qrammatika', 'Danışıq klubları', 'Mətn işləri', 'Sertifikat hazırlığı'],
    requirements: ['Rus dili bilən şagirdlər üçün', 'Başlanğıc Azərbaycan dili biliyi'],
    outcomes: ['Azərbaycan dilində sərbəst danışa bilmək'],
    targetAudience: 'Rus bölməsi şagirdləri',
    level: 'Orta',
    certificate: true,
  },
  
  // Sınaq imtahanları
  {
    title: 'Sınaq imtahanı: 9-cu sinif',
    description: '9-cu sinif şagirdləri üçün həftəlik sınaq imtahanları. DİM formatında.',
    slug: 'sinaq-imtahani-9-cu-sinif',
    icon: 'Users',
    color: 'purple',
    href: '/sinaq-imtahani',
    features: ['Hər həftə', 'DİM formatı', 'Nəticə analizi', 'Səhv işləri'],
    duration: 'Həftəlik',
    students: '150+',
    displayOrder: 17,
    isActive: true,
    fullDescription: '9-cu sinif şagirdləri üçün həftəlik sınaq imtahanları. DİM formatında keçirilir.',
    lessons: 0,
    hours: 0,
    teacher: '',
    price: '20 AZN/imtahan',
    program: [],
    requirements: ['9-cu sinif şagirdləri üçün'],
    outcomes: ['İmtahan formatına alışmaq'],
    targetAudience: '9-cu sinif şagirdləri',
    level: 'Hər səviyyə',
    certificate: false,
  },
  {
    title: 'Sınaq imtahanı: Qəbul (I-IV qrup)',
    description: 'Qəbul imtahanına hazırlaşanlar üçün həftəlik sınaqlar. Bütün qruplar üzrə.',
    slug: 'sinaq-imtahani-qebul',
    icon: 'Users',
    color: 'purple',
    href: '/sinaq-imtahani',
    features: ['Hər həftə', '4 qrup', 'Online nəticə', 'Reytinq'],
    duration: 'Həftəlik',
    students: '200+',
    displayOrder: 18,
    isActive: true,
    fullDescription: 'Qəbul imtahanına hazırlaşanlar üçün həftəlik sınaq imtahanları. Bütün qruplar üzrə.',
    lessons: 0,
    hours: 0,
    teacher: '',
    price: '25 AZN/imtahan',
    program: [],
    requirements: ['Qəbul imtahanına hazırlaşanlar üçün'],
    outcomes: ['İmtahan formatına alışmaq', 'Nəticə analizi'],
    targetAudience: 'Qəbul imtahanına hazırlaşanlar',
    level: 'Hər səviyyə',
    certificate: false,
  },
];

async function seedCourses() {
  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/azeriedu_local';
  
  try {
    const client = new MongoClient(uri);
    await client.connect();
    console.log('MongoDB-yə qoşuldu');

    const db = client.db();
    const coursesCollection = db.collection('courses');

    // Əvvəlcə mövcud kursları təmizlə
    await coursesCollection.deleteMany({});
    console.log('Köhnə kurslar təmizləndi');

    // Yeni kursları əlavə et
    const result = await coursesCollection.insertMany(courses);
    console.log(`${result.insertedCount} kurs uğurla əlavə edildi`);

    await client.close();
    console.log('Bağlandı');
  } catch (error) {
    console.error('Xəta:', error);
    process.exit(1);
  }
}

seedCourses();